### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'list' objects

### ISSUE THREAD

**Issue by snowfrogdev** [udevbe/tinyh264#2]
When running rake inside the wasm folder I can this:

```
emcc (Emscripten gcc/clang-like replacement) 1.38.22 ((unknown revision))
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Ready to go
emcc ../src/h264bsd_byte_stream.c ../src/h264bsd_cavlc.c ../src/h264bsd_conceal.c ../src/h264bsd_deblocking.c ../src/h264bsd_decoder.c ../src/h264bsd_dpb.c ../src/h264bsd_image.c ../src/h264bsd_inter_prediction.c ../src/h264bsd_intra_prediction.c ../src/h264bsd_macroblock_layer.c ../src/h264bsd_nal_unit.c ../src/h264bsd_neighbour.c ../src/h264bsd_pic_order_cnt.c ../src/h264bsd_pic_param_set.c ../src/h264bsd_reconstruct.c ../src/h264bsd_sei.c ../src/h264bsd_seq_param_set.c ../src/h264bsd_slice_data.c ../src/h264bsd_slice_group_map.c ../src/h264bsd_slice_header.c ../src/h264bsd_storage.c ../src/h264bsd_stream.c ../src/h264bsd_transform.c ../src/h264bsd_util.c ../src/h264bsd_vlc.c ../src/h264bsd_vui.c -O3 --memory-init-file 0 --llvm-opts "['-tti', '-domtree', '-tti', '-domtree', '-deadargelim', '-domtree', '-instcombine', '-domtree', '-jump-threading', '-domtree', '-instcombine', '-reassociate', '-domtree', '-loops', '-loop-rotate', '-licm', '-domtree', '-instcombine', '-loops', '-loop-idiom', '-loop-unroll', '-memdep', '-memdep', '-memcpyopt', '-domtree', '-demanded-bits', '-instcombine', '-jump-threading', '-domtree', '-memdep', '-loops', '-licm', '-adce', '-domtree', '-instcombine', '-elim-avail-extern', '-float2int', '-domtree', '-loops', '-loop-rotate', '-demanded-bits', '-instcombine', '-domtree', '-instcombine', '-loops', '-loop-unroll', '-instcombine', '-licm', '-strip-dead-prototypes', '-domtree']" --llvm-lto 3 -s USE_CLOSURE_COMPILER=1 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s NO_EXIT_RUNTIME=1 -s NO_FILESYSTEM=1 -s INVOKE_RUN=0 -s DOUBLE_MODE=0 -s PRECISE_I64_MATH=0 -s ALLOW_MEMORY_GROWTH=1 -s WASM=1 -s EXTRA_EXPORTED_RUNTIME_METHODS='["getValue"]' -s EXPORTED_FUNCTIONS='["_malloc","_free","_h264bsdAlloc","_h264bsdFree","_h264bsdInit","_h264bsdDecode","_h264bsdShutdown"]' -o TinyH264.js
Traceback (most recent call last):
  File "C:\emsdk-master\emscripten\1.38.22\emcc.py", line 3088, in <module>
    sys.exit(run())
  File "C:\emsdk-master\emscripten\1.38.22\emcc.py", line 1121, in run
    shared.Settings.EXPORTED_FUNCTIONS += ['_malloc', '_free']
TypeError: cannot concatenate 'str' and 'list' objects
rake aborted!
Command failed with status (1): [emcc ../src/h264bsd_byte_stream.c ../src/h...]
C:/Users/phili/Documents/GitHub/tinyh264-master/wasm/Rakefile:24:in `block in <top (required)>'
Tasks: TOP => default => TinyH264.js
(See full trace by running task with --trace)
```

**Comment by Zubnix** [comment]
My guess is that this is a windows issue or emscripten on windows issue. Build works fine in linux. See also: https://github.com/udevbe/greenfield/blob/master/wasmlibs/build_all.sh
