### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by fernandoc1** [udevbe/tinyh264#4]
I'm trying to compile the source code, and it is giving the following error:
I'm using Ubuntu 18.04 with emcc and rake from repository:
emcc (Emscripten GCC-like replacement) 1.22.1 ()

```emcc --version
emcc (Emscripten GCC-like replacement) 1.22.1 ()
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  
Ready to go
emcc ../src/h264bsd_byte_stream.c ../src/h264bsd_cavlc.c ../src/h264bsd_conceal.c ../src/h264bsd_deblocking.c ../src/h264bsd_decoder.c ../src/h264bsd_dpb.c ../src/h264bsd_image.c ../src/h264bsd_inter_prediction.c ../src/h264bsd_intra_prediction.c ../src/h264bsd_macroblock_layer.c ../src/h264bsd_nal_unit.c ../src/h264bsd_neighbour.c ../src/h264bsd_pic_order_cnt.c ../src/h264bsd_pic_param_set.c ../src/h264bsd_reconstruct.c ../src/h264bsd_sei.c ../src/h264bsd_seq_param_set.c ../src/h264bsd_slice_data.c ../src/h264bsd_slice_group_map.c ../src/h264bsd_slice_header.c ../src/h264bsd_storage.c ../src/h264bsd_stream.c ../src/h264bsd_transform.c ../src/h264bsd_util.c ../src/h264bsd_vlc.c ../src/h264bsd_vui.c -O3 --memory-init-file 0 --llvm-opts "['-tti', '-domtree', '-tti', '-domtree', '-deadargelim', '-domtree', '-instcombine', '-domtree', '-jump-threading', '-domtree', '-instcombine', '-reassociate', '-domtree', '-loops', '-loop-rotate', '-licm', '-domtree', '-instcombine', '-loops', '-loop-idiom', '-loop-unroll', '-memdep', '-memdep', '-memcpyopt', '-domtree', '-demanded-bits', '-instcombine', '-jump-threading', '-domtree', '-memdep', '-loops', '-licm', '-adce', '-domtree', '-instcombine', '-elim-avail-extern', '-float2int', '-domtree', '-loops', '-loop-rotate', '-demanded-bits', '-instcombine', '-domtree', '-instcombine', '-loops', '-loop-unroll', '-instcombine', '-licm', '-strip-dead-prototypes', '-domtree']" --llvm-lto 3 -s USE_CLOSURE_COMPILER=1 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s NO_EXIT_RUNTIME=1 -s NO_FILESYSTEM=1 -s INVOKE_RUN=0 -s DOUBLE_MODE=0 -s ALLOW_MEMORY_GROWTH=1 -s WASM=1 -s EXTRA_EXPORTED_RUNTIME_METHODS='["getValue"]' -s EXPORTED_FUNCTIONS='["_malloc","_free","_h264bsdAlloc","_h264bsdFree","_h264bsdInit","_h264bsdDecode","_h264bsdShutdown"]' -o TinyH264.js
WARNING  root: Assigning a non-existent settings attribute "USE_CLOSURE_COMPILER"
WARNING  root:  - did you mean one of CLOSURE_COMPILER?
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root: Assigning a non-existent settings attribute "NO_FILESYSTEM"
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root: Assigning a non-existent settings attribute "WASM"
WARNING  root:  - did you mean one of ASM_JS?
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root: Assigning a non-existent settings attribute "EXTRA_EXPORTED_RUNTIME_METHODS"
WARNING  root:  - did you mean one of ORIGINAL_EXPORTED_FUNCTIONS, EXPORTED_FUNCTIONS?
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
WARNING  root: Disabling asm.js validation for memory growth (memory can grow, but you lose some amount of speed)
opt: Unknown command line argument '-disable-internalize'.  Try: '/usr/bin/opt -help'
opt: Did you mean '-disable-preinline'?
Traceback (most recent call last):
  File "/usr/bin/emcc", line 1604, in <module>
    shared.Building.llvm_opt(final, link_opts, final + '.link.ll')
  File "/usr/share/emscripten/tools/shared.py", line 1357, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 
rake aborted!
Command failed with status (1): [emcc ../src/h264bsd_byte_stream.c ../src/h...]
/home/fccoelho/Code/tinyh264/wasm/Rakefile:24:in `block in <top (required)>'
Tasks: TOP => default => TinyH264.js
(See full trace by running task with --trace)
`

**Comment by Zubnix** [comment]
it seems the version of emscripten you use is very old? Current version is 1.39.1, you seem to be using 1.22.1, as a result a lot of compilation options are not recognized. More info about the latest version here: https://emscripten.org/docs/getting_started/downloads.html#installation-instructions

**Comment by fernandoc1** [comment]
Thanks for the explanation.
That solved the compilation problem.
