### ISSUE TITLE
help

### ISSUE THREAD

**Issue by yangdg1234** [udevbe/tinyh264#7]
yangdg@ubuntu:~/tinyh264-master/lib$ node index.js
/home/yangdg/tinyh264-master/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import { init } from './TinyH264Worker';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Hi,  please help me,  i  want to play main profile h264 stream using HTML5,  i searched on the internet , i got broadway h264 decoder, but it only works for baseline h264,  then i find tinyh264, 
it seems meet my needs,  but when i finally npm run build ok,  i still don't know to get it work. any 
help will be appreciate, thanks.

**Comment by Zubnix** [comment]
`index.js` is not supposed to be invoked using node. Instead tinyh264 is meant to be used as a library in the static javascript of your website (using ie `webpack`). Have a look at the `demo` folder.

**Comment by yangdg1234** [comment]
H264NALDecoder.worker.js:5 Uncaught TypeError: Object(...) is not a function
    at eval (H264NALDecoder.worker.js:5)
    at Module../src/H264NALDecoder.worker.js (311b1ac0ffed377baa0e.worker.js:120)
    at __webpack_require__ (311b1ac0ffed377baa0e.worker.js:20)
    at 311b1ac0ffed377baa0e.worker.js:84
    at 311b1ac0ffed377baa0e.worker.js:87


appreciate your response,    i  have try the demo,  and execute yarn start:dev ok,  then i open the chrome  http://localhost:8080/dist/,  then i get above errors,  what's the matter?  do you try it ok?

**Comment by Zubnix** [comment]
For above error See #6 Let me know if it works for you.

**Comment by yangdg1234** [comment]
ok, greate job, the demo works,  thank you for your patience :)
